[chain.rinkeby]
network-id=4
rpc-endpoints=["http://1.geth.testnet.golem.network:55555"]
currency-symbol="tETH"
priority-fee=1.5111
max-fee-per-gas=500.0
transaction-timeout=100
token = { address="0xd94e3DC39d4Cad1DAd634e7eb585A57A19dC7EFE", symbol="tGLM" }

[chain.goerli]
network-id=5
rpc-endpoints = ["https://ethereum-goerli-rpc.allthatnode.com",
    "https://rpc.goerli.mudit.blog",
    "https://rpc.slock.it/goerli",
    "https://www.ethercluster.com/goerli",
    "https://rpc.ankr.com/eth_goerli"]
currency-symbol="tETH"
priority-fee=1.5111
max-fee-per-gas=500.0
transaction-timeout=100
token = { address="0x33af15c79d64b85ba14aaffaa4577949104b22e8", symbol="tGLM" }
multi-contract = { address="0x7777784f803a7bf1d7f115f849d29ce5706da64a" }

[chain.mumbai]
network-id=80001
rpc-endpoints = ["https://rpc-mumbai.maticvigil.com/v1/fd04db1066cae0f44d3461ae6d6a7cbbdd46e4a5", "https://rpc-mumbai.matic.today"]
currency-symbol="tMATIC"
priority-fee=1.5111
max-fee-per-gas=500.0
transaction-timeout=100
token = { address = "0x2036807B0B3aaf5b1858EE822D0e111fDdac7018", symbol="tGLM" }
multi-contract = { address="0x800010D7d0d315DCA795110ecCf0127cBd76b89f" }

[chain.polygon]
network-id=137
rpc-endpoints = ["https://polygon-rpc.com"]
currency-symbol="MATIC"
priority-fee=30.111
max-fee-per-gas=500.0
transaction-timeout=100
token = { address = "0x2036807B0B3aaf5b1858EE822D0e111fDdac7018", symbol="tGLM" }
multi-contract = { address="0x50100d4faf5f3b09987dea36dc2eddd57a3e561b" }
