services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u setup_chain.py
    volumes:
      - ./.ethash/:/root/.ethash/
    ports:
      - '8545:8545'
